### ISSUE TITLE
Release 2.0.0 - Task list

### ISSUE THREAD

**Issue by righettod** [righettod/log-requests-to-sqlite#47]
Source: #45 

- [x] Add an option to made the logging of the HTTP Reponse optional
- [x] Test the extension with this new option on several real assessments to ensure that it do not break burp.
- [x] If OK, release the 2.0.0 in the repository.
- [x] Release the 2.0.0 on the store.
